CREATE SCHEMA IF NOT EXISTS ot_ssmw7150cne;

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  image TEXT,
  role TEXT NOT NULL DEFAULT '管理员',
  addtime TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.yonghu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  yonghuzhanghao TEXT NOT NULL UNIQUE,
  mima TEXT NOT NULL,
  yonghuxingming TEXT NOT NULL,
  xingbie TEXT,
  nianling INTEGER DEFAULT 1,
  shoujihao TEXT,
  shenfenzheng TEXT,
  dizhi TEXT,
  touxiang TEXT
);

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.huodongguanliyuan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  guanlizhanghao TEXT NOT NULL UNIQUE,
  mima TEXT NOT NULL,
  guanlixingming TEXT NOT NULL,
  xingbie TEXT,
  nianling TEXT,
  youxiang TEXT,
  shoujihao TEXT,
  shenfenzheng TEXT,
  touxiang TEXT
);

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.huodongfenlei (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  huodongfenlei TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.huodongxinxi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  huodongmingcheng TEXT NOT NULL,
  huodongfenlei TEXT NOT NULL,
  huodongtupian TEXT,
  huodongdidian TEXT,
  kaishishijian TIMESTAMPTZ,
  jieshushijian TIMESTAMPTZ,
  kecanyurenshu INTEGER DEFAULT 0,
  baomingyaoqiu TEXT,
  huodongmiaoshu TEXT,
  thumbsupnum INTEGER DEFAULT 0,
  crazilynum INTEGER DEFAULT 0,
  clicktime TIMESTAMPTZ,
  clicknum INTEGER DEFAULT 0,
  discussnum INTEGER DEFAULT 0,
  storeupnum INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.baomingxinxi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  huodongmingcheng TEXT,
  huodongfenlei TEXT,
  huodongtupian TEXT,
  huodongdidian TEXT,
  kaishishijian TEXT,
  jieshushijian TEXT,
  kecanyurenshu INTEGER DEFAULT 1,
  baomingshijian TIMESTAMPTZ,
  yonghuzhanghao TEXT,
  yonghuxingming TEXT,
  crossuserid BIGINT,
  crossrefid BIGINT,
  sfsh TEXT DEFAULT '待审核',
  shhf TEXT
);

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.huodonggenzong (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  huodongmingcheng TEXT NOT NULL,
  huodongfenlei TEXT NOT NULL,
  huodongtupian TEXT,
  huodongdidian TEXT,
  kaishishijian TEXT,
  jieshushijian TEXT,
  huodongzhuangtai TEXT DEFAULT '报名中'
);

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.tongzhixinxi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  yonghuzhanghao TEXT,
  yonghuxingming TEXT,
  tongzhibiaoti TEXT,
  fengmian TEXT,
  tongzhishijian TIMESTAMPTZ,
  tongzhineirong TEXT
);

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  title TEXT NOT NULL,
  introduction TEXT,
  typename TEXT,
  name TEXT,
  headportrait TEXT,
  clicknum INTEGER DEFAULT 0,
  clicktime TIMESTAMPTZ,
  thumbsupnum INTEGER DEFAULT 0,
  crazilynum INTEGER DEFAULT 0,
  storeupnum INTEGER DEFAULT 0,
  picture TEXT,
  content TEXT,
  istop INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.storeup (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  userid BIGINT NOT NULL,
  refid BIGINT NOT NULL,
  tablename TEXT,
  name TEXT,
  picture TEXT,
  type TEXT DEFAULT '1',
  inteltype TEXT,
  remark TEXT
);

CREATE TABLE IF NOT EXISTS ot_ssmw7150cne.discusshuodongxinxi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  addtime TIMESTAMPTZ DEFAULT now(),
  refid BIGINT NOT NULL,
  userid BIGINT NOT NULL,
  avatarurl TEXT,
  nickname TEXT,
  content TEXT NOT NULL,
  reply TEXT,
  thumbsupnum INTEGER DEFAULT 0,
  crazilynum INTEGER DEFAULT 0,
  istop INTEGER DEFAULT 0,
  tuserids TEXT,
  cuserids TEXT
);

INSERT INTO ot_ssmw7150cne.users (id, username, password, image, role, addtime) VALUES
  (1, 'admin', 'admin', 'upload/image1.jpg', '管理员', '2025-01-25 08:56:04+00')
ON CONFLICT (id) DO UPDATE SET username = EXCLUDED.username, password = EXCLUDED.password, image = EXCLUDED.image, role = EXCLUDED.role;

INSERT INTO ot_ssmw7150cne.yonghu (id, addtime, yonghuzhanghao, mima, yonghuxingming, xingbie, nianling, shoujihao, shenfenzheng, dizhi, touxiang) VALUES
  (11, '2025-01-25 08:56:04+00', '用户账号1', '123456', '用户姓名1', '男', 1, '13823888881', '演示身份证1', '演示住址1', 'upload/yonghu_touxiang1.jpg'),
  (12, '2025-01-25 08:56:04+00', '用户账号2', '123456', '用户姓名2', '女', 2, '13823888882', '演示身份证2', '演示住址2', 'upload/yonghu_touxiang2.jpg'),
  (13, '2025-01-25 08:56:04+00', '用户账号3', '123456', '用户姓名3', '男', 3, '13823888883', '演示身份证3', '演示住址3', 'upload/yonghu_touxiang3.jpg')
ON CONFLICT (id) DO UPDATE SET yonghuzhanghao = EXCLUDED.yonghuzhanghao, mima = EXCLUDED.mima, yonghuxingming = EXCLUDED.yonghuxingming, xingbie = EXCLUDED.xingbie, nianling = EXCLUDED.nianling, shoujihao = EXCLUDED.shoujihao, shenfenzheng = EXCLUDED.shenfenzheng, dizhi = EXCLUDED.dizhi, touxiang = EXCLUDED.touxiang;

INSERT INTO ot_ssmw7150cne.huodongguanliyuan (id, addtime, guanlizhanghao, mima, guanlixingming, xingbie, nianling, youxiang, shoujihao, shenfenzheng, touxiang) VALUES
  (21, '2025-01-25 08:56:04+00', '管理账号1', '123456', '管理姓名1', '男', '25', 'manager1@example.com', '13823888881', '演示身份证1', 'upload/huodongguanliyuan_touxiang1.jpg'),
  (22, '2025-01-25 08:56:04+00', '管理账号2', '123456', '管理姓名2', '女', '26', 'manager2@example.com', '13823888882', '演示身份证2', 'upload/huodongguanliyuan_touxiang2.jpg'),
  (23, '2025-01-25 08:56:04+00', '管理账号3', '123456', '管理姓名3', '男', '27', 'manager3@example.com', '13823888883', '演示身份证3', 'upload/huodongguanliyuan_touxiang3.jpg')
ON CONFLICT (id) DO UPDATE SET guanlizhanghao = EXCLUDED.guanlizhanghao, mima = EXCLUDED.mima, guanlixingming = EXCLUDED.guanlixingming, xingbie = EXCLUDED.xingbie, nianling = EXCLUDED.nianling, youxiang = EXCLUDED.youxiang, shoujihao = EXCLUDED.shoujihao, shenfenzheng = EXCLUDED.shenfenzheng, touxiang = EXCLUDED.touxiang;

INSERT INTO ot_ssmw7150cne.huodongfenlei (id, addtime, huodongfenlei) VALUES
  (1, '2025-01-25 08:56:04+00', '志愿服务'),
  (2, '2025-01-25 08:56:04+00', '文体活动'),
  (3, '2025-01-25 08:56:04+00', '讲座培训'),
  (4, '2025-01-25 08:56:04+00', '社区共建')
ON CONFLICT (id) DO UPDATE SET huodongfenlei = EXCLUDED.huodongfenlei;

INSERT INTO ot_ssmw7150cne.huodongxinxi (id, addtime, huodongmingcheng, huodongfenlei, huodongtupian, huodongdidian, kaishishijian, jieshushijian, kecanyurenshu, baomingyaoqiu, huodongmiaoshu, thumbsupnum, crazilynum, clicktime, clicknum, discussnum, storeupnum) VALUES
  (1, '2025-01-25 08:56:04+00', '校园志愿服务', '志愿服务', 'upload/huodongxinxi_huodongtupian1.jpg', '综合楼广场', '2025-01-25 16:56:04+00', '2025-01-25 18:56:04+00', 40, '报名后请准时签到', '组织同学参与校园公共区域引导和服务。', 12, 0, '2025-01-26 00:00:00+00', 86, 2, 5),
  (2, '2025-01-25 08:56:04+00', '社团篮球友谊赛', '文体活动', 'upload/huodongxinxi_huodongtupian2.jpg', '体育馆', '2025-01-26 15:00:00+00', '2025-01-26 17:30:00+00', 24, '自备运动装备', '面向校内社团的篮球交流活动。', 8, 1, '2025-01-26 00:00:00+00', 64, 1, 4),
  (3, '2025-01-25 08:56:04+00', '就业经验分享会', '讲座培训', 'upload/huodongxinxi_huodongtupian3.jpg', '报告厅 A101', '2025-01-27 19:00:00+00', '2025-01-27 21:00:00+00', 120, '提前十分钟入场', '邀请毕业生分享求职准备和面试经验。', 16, 0, '2025-01-26 00:00:00+00', 132, 3, 9),
  (4, '2025-01-25 08:56:04+00', '社区清洁共建', '社区共建', 'upload/huodongxinxi_huodongtupian4.jpg', '东门社区', '2025-01-28 09:00:00+00', '2025-01-28 11:30:00+00', 60, '穿着便于活动的衣物', '联合社区开展清洁和宣传活动。', 10, 0, '2025-01-26 00:00:00+00', 78, 1, 6)
ON CONFLICT (id) DO UPDATE SET huodongmingcheng = EXCLUDED.huodongmingcheng, huodongfenlei = EXCLUDED.huodongfenlei, huodongtupian = EXCLUDED.huodongtupian, huodongdidian = EXCLUDED.huodongdidian, kaishishijian = EXCLUDED.kaishishijian, jieshushijian = EXCLUDED.jieshushijian, kecanyurenshu = EXCLUDED.kecanyurenshu, baomingyaoqiu = EXCLUDED.baomingyaoqiu, huodongmiaoshu = EXCLUDED.huodongmiaoshu, thumbsupnum = EXCLUDED.thumbsupnum, crazilynum = EXCLUDED.crazilynum, clicktime = EXCLUDED.clicktime, clicknum = EXCLUDED.clicknum, discussnum = EXCLUDED.discussnum, storeupnum = EXCLUDED.storeupnum;

INSERT INTO ot_ssmw7150cne.baomingxinxi (id, addtime, huodongmingcheng, huodongfenlei, huodongtupian, huodongdidian, kaishishijian, jieshushijian, kecanyurenshu, baomingshijian, yonghuzhanghao, yonghuxingming, crossuserid, crossrefid, sfsh, shhf) VALUES
  (1, '2025-01-25 08:56:04+00', '校园志愿服务', '志愿服务', 'upload/baomingxinxi_huodongtupian1.jpg', '综合楼广场', '2025-01-25 16:56:04', '2025-01-25 18:56:04', 1, '2025-01-25 16:56:04+00', '用户账号1', '用户姓名1', 11, 1, '是', '报名通过'),
  (2, '2025-01-25 08:56:04+00', '社团篮球友谊赛', '文体活动', 'upload/baomingxinxi_huodongtupian2.jpg', '体育馆', '2025-01-26 15:00:00', '2025-01-26 17:30:00', 1, '2025-01-25 16:58:04+00', '用户账号2', '用户姓名2', 12, 2, '待审核', ''),
  (3, '2025-01-25 08:56:04+00', '就业经验分享会', '讲座培训', 'upload/baomingxinxi_huodongtupian3.jpg', '报告厅 A101', '2025-01-27 19:00:00', '2025-01-27 21:00:00', 1, '2025-01-25 17:01:04+00', '用户账号3', '用户姓名3', 13, 3, '是', '请按时参加'),
  (4, '2025-01-25 08:56:04+00', '社区清洁共建', '社区共建', 'upload/baomingxinxi_huodongtupian4.jpg', '东门社区', '2025-01-28 09:00:00', '2025-01-28 11:30:00', 1, '2025-01-25 17:05:04+00', '用户账号1', '用户姓名1', 11, 4, '否', '名额已满')
ON CONFLICT (id) DO UPDATE SET huodongmingcheng = EXCLUDED.huodongmingcheng, huodongfenlei = EXCLUDED.huodongfenlei, huodongtupian = EXCLUDED.huodongtupian, huodongdidian = EXCLUDED.huodongdidian, kaishishijian = EXCLUDED.kaishishijian, jieshushijian = EXCLUDED.jieshushijian, kecanyurenshu = EXCLUDED.kecanyurenshu, baomingshijian = EXCLUDED.baomingshijian, yonghuzhanghao = EXCLUDED.yonghuzhanghao, yonghuxingming = EXCLUDED.yonghuxingming, crossuserid = EXCLUDED.crossuserid, crossrefid = EXCLUDED.crossrefid, sfsh = EXCLUDED.sfsh, shhf = EXCLUDED.shhf;

INSERT INTO ot_ssmw7150cne.huodonggenzong (id, addtime, huodongmingcheng, huodongfenlei, huodongtupian, huodongdidian, kaishishijian, jieshushijian, huodongzhuangtai) VALUES
  (1, '2025-01-25 08:56:04+00', '校园志愿服务', '志愿服务', 'upload/huodonggenzong_huodongtupian1.jpg', '综合楼广场', '2025-01-25 16:56:04', '2025-01-25 18:56:04', '报名中'),
  (2, '2025-01-25 08:56:04+00', '社团篮球友谊赛', '文体活动', 'upload/huodonggenzong_huodongtupian2.jpg', '体育馆', '2025-01-26 15:00:00', '2025-01-26 17:30:00', '进行中'),
  (3, '2025-01-25 08:56:04+00', '就业经验分享会', '讲座培训', 'upload/huodonggenzong_huodongtupian3.jpg', '报告厅 A101', '2025-01-27 19:00:00', '2025-01-27 21:00:00', '报名中')
ON CONFLICT (id) DO UPDATE SET huodongmingcheng = EXCLUDED.huodongmingcheng, huodongfenlei = EXCLUDED.huodongfenlei, huodongtupian = EXCLUDED.huodongtupian, huodongdidian = EXCLUDED.huodongdidian, kaishishijian = EXCLUDED.kaishishijian, jieshushijian = EXCLUDED.jieshushijian, huodongzhuangtai = EXCLUDED.huodongzhuangtai;

INSERT INTO ot_ssmw7150cne.tongzhixinxi (id, addtime, yonghuzhanghao, yonghuxingming, tongzhibiaoti, fengmian, tongzhishijian, tongzhineirong) VALUES
  (1, '2025-01-25 08:56:04+00', '用户账号1', '用户姓名1', '报名审核通过通知', 'upload/tongzhixinxi_fengmian1.jpg', '2025-01-25 16:56:04+00', '你的校园志愿服务报名已通过，请准时到场。'),
  (2, '2025-01-25 08:56:04+00', '用户账号2', '用户姓名2', '活动时间提醒', 'upload/tongzhixinxi_fengmian2.jpg', '2025-01-26 09:00:00+00', '社团篮球友谊赛将在下午开始，请提前热身。'),
  (3, '2025-01-25 08:56:04+00', '用户账号3', '用户姓名3', '讲座入场提醒', 'upload/tongzhixinxi_fengmian3.jpg', '2025-01-27 12:00:00+00', '就业经验分享会请提前十分钟入场。')
ON CONFLICT (id) DO UPDATE SET yonghuzhanghao = EXCLUDED.yonghuzhanghao, yonghuxingming = EXCLUDED.yonghuxingming, tongzhibiaoti = EXCLUDED.tongzhibiaoti, fengmian = EXCLUDED.fengmian, tongzhishijian = EXCLUDED.tongzhishijian, tongzhineirong = EXCLUDED.tongzhineirong;

INSERT INTO ot_ssmw7150cne.news (id, addtime, title, introduction, typename, name, headportrait, clicknum, clicktime, thumbsupnum, crazilynum, storeupnum, picture, content, istop) VALUES
  (1, '2025-01-25 08:56:04+00', '活动报名系统上线', '活动报名、审核和通知流程已经开放演示。', '平台公告', '管理员', 'upload/image1.jpg', 32, '2025-01-25 16:56:04+00', 4, 0, 2, 'upload/news_picture1.jpg', '演示版用于展示活动管理平台的核心流程。', 1),
  (2, '2025-01-25 08:56:04+00', '志愿服务招募', '欢迎同学报名参与校园志愿服务。', '活动资讯', '活动管理员', 'upload/image1.jpg', 46, '2025-01-25 16:56:04+00', 8, 0, 3, 'upload/news_picture2.jpg', '志愿服务活动需要提前报名并按时签到。', 0)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, introduction = EXCLUDED.introduction, typename = EXCLUDED.typename, name = EXCLUDED.name, headportrait = EXCLUDED.headportrait, clicknum = EXCLUDED.clicknum, clicktime = EXCLUDED.clicktime, thumbsupnum = EXCLUDED.thumbsupnum, crazilynum = EXCLUDED.crazilynum, storeupnum = EXCLUDED.storeupnum, picture = EXCLUDED.picture, content = EXCLUDED.content, istop = EXCLUDED.istop;

INSERT INTO ot_ssmw7150cne.storeup (id, addtime, userid, refid, tablename, name, picture, type, inteltype, remark) VALUES
  (1, '2025-01-25 08:56:04+00', 11, 1, 'huodongxinxi', '校园志愿服务', 'upload/huodongxinxi_huodongtupian1.jpg', '1', '志愿服务', '用户收藏活动'),
  (2, '2025-01-25 08:56:04+00', 12, 3, 'huodongxinxi', '就业经验分享会', 'upload/huodongxinxi_huodongtupian3.jpg', '1', '讲座培训', '用户收藏活动')
ON CONFLICT (id) DO UPDATE SET userid = EXCLUDED.userid, refid = EXCLUDED.refid, tablename = EXCLUDED.tablename, name = EXCLUDED.name, picture = EXCLUDED.picture, type = EXCLUDED.type, inteltype = EXCLUDED.inteltype, remark = EXCLUDED.remark;

INSERT INTO ot_ssmw7150cne.discusshuodongxinxi (id, addtime, refid, userid, avatarurl, nickname, content, reply, thumbsupnum, crazilynum, istop, tuserids, cuserids) VALUES
  (1, '2025-01-25 08:56:04+00', 1, 11, 'upload/yonghu_touxiang1.jpg', '用户账号1', '活动安排很清楚。', '感谢反馈。', 3, 0, 0, '', ''),
  (2, '2025-01-25 08:56:04+00', 3, 12, 'upload/yonghu_touxiang2.jpg', '用户账号2', '希望后续多开职业规划类讲座。', '', 2, 0, 0, '', '')
ON CONFLICT (id) DO UPDATE SET refid = EXCLUDED.refid, userid = EXCLUDED.userid, avatarurl = EXCLUDED.avatarurl, nickname = EXCLUDED.nickname, content = EXCLUDED.content, reply = EXCLUDED.reply, thumbsupnum = EXCLUDED.thumbsupnum, crazilynum = EXCLUDED.crazilynum, istop = EXCLUDED.istop, tuserids = EXCLUDED.tuserids, cuserids = EXCLUDED.cuserids;

SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.users', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.users), 1), true);
SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.yonghu', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.yonghu), 1), true);
SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.huodongguanliyuan', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.huodongguanliyuan), 1), true);
SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.huodongfenlei', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.huodongfenlei), 1), true);
SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.huodongxinxi', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.huodongxinxi), 1), true);
SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.baomingxinxi', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.baomingxinxi), 1), true);
SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.huodonggenzong', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.huodonggenzong), 1), true);
SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.tongzhixinxi', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.tongzhixinxi), 1), true);
SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.news', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.news), 1), true);
SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.storeup', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.storeup), 1), true);
SELECT setval(pg_get_serial_sequence('ot_ssmw7150cne.discusshuodongxinxi', 'id'), COALESCE((SELECT MAX(id) FROM ot_ssmw7150cne.discusshuodongxinxi), 1), true);

CREATE OR REPLACE FUNCTION public.ot_ssmw7150cne_rest(
  p_table_name TEXT,
  p_method TEXT DEFAULT 'GET',
  p_query JSONB DEFAULT '{}'::jsonb,
  p_payload JSONB DEFAULT '{}'::jsonb
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_schema CONSTANT TEXT := 'ot_ssmw7150cne';
  v_table TEXT;
  v_sql TEXT;
  v_rows JSONB := '[]'::jsonb;
  v_key TEXT;
  v_value TEXT;
  v_where TEXT := '';
  v_order TEXT := '';
  v_limit TEXT := '';
  v_set TEXT := '';
  v_columns TEXT := '';
  v_values TEXT := '';
BEGIN
  IF p_table_name NOT IN ('users', 'yonghu', 'huodongguanliyuan', 'huodongfenlei', 'huodongxinxi', 'baomingxinxi', 'huodonggenzong', 'tongzhixinxi', 'news', 'storeup', 'discusshuodongxinxi') THEN
    RAISE EXCEPTION 'table is not allowed: %', p_table_name;
  END IF;

  v_table := format('%I.%I', v_schema, p_table_name);

  FOR v_key, v_value IN SELECT key, value #>> '{}' FROM jsonb_each(p_query)
  LOOP
    IF v_key = 'select' THEN
      CONTINUE;
    ELSIF v_key = 'order' THEN
      v_order := ' ORDER BY ' || quote_ident(split_part(v_value, '.', 1)) ||
        CASE WHEN lower(split_part(v_value, '.', 2)) = 'desc' THEN ' DESC' ELSE ' ASC' END;
    ELSIF v_key = 'limit' THEN
      v_limit := ' LIMIT ' || LEAST(GREATEST(v_value::int, 1), 200);
    ELSIF v_value LIKE 'eq.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' = ' || quote_literal(substring(v_value FROM 4));
    ELSIF v_value LIKE 'ilike.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' ILIKE ' || quote_literal(substring(v_value FROM 7));
    END IF;
  END LOOP;

  IF upper(p_method) = 'GET' THEN
    v_sql := 'SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM (SELECT * FROM ' || v_table || v_where || v_order || v_limit || ') t';
    EXECUTE v_sql INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'POST' THEN
    SELECT string_agg(quote_ident(key), ', '), string_agg(quote_literal(value #>> '{}'), ', ')
      INTO v_columns, v_values
    FROM jsonb_each(p_payload)
    WHERE key <> 'id';
    IF v_columns IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'INSERT INTO ' || v_table || ' (' || v_columns || ') VALUES (' || v_values || ') RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'PATCH' THEN
    SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value #>> '{}'), ', ')
      INTO v_set
    FROM jsonb_each(p_payload)
    WHERE key <> 'id';
    IF v_set IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'UPDATE ' || v_table || ' SET ' || v_set || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'DELETE' THEN
    v_sql := 'DELETE FROM ' || v_table || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  END IF;

  RAISE EXCEPTION 'method is not allowed: %', p_method;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ot_ssmw7150cne_rest(TEXT, TEXT, JSONB, JSONB) TO anon, authenticated, service_role;
